spring:
  datasource:
    url: jdbc:sqlserver://java-app.database.windows.net:1433;database=java-app;user=java-app@java-app;password=Admin@123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: java-app
    password: Admin@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080
